name: talks_nicoguaro
channels:
- conda-forge
- anaconda
dependencies:
- anaconda::python=3.6.8
- conda-forge::numpy
- conda-forge::scipy
- conda-forge::matplotlib=3.1.3
- conda-forge::ipython=7.12.0
- conda-forge::notebook=6.0.3
- conda-forge::ipywidgets=7.5.1
- conda-forge::rise=5.6.0
# FIE talk
- sympy
- jupyter
- ipykernel
- pip
- pip:
  - meshio==3.0
  - solidspy==1.0.16
